flat_create_database.Rmd:
  path: dev/flat_create_database.Rmd
  state: active
  R:
  - R/create_hedonic_table.R
  - R/create_profiles_table.R
  - R/create_toy_data.R
  - R/save_data_in_db.R
  tests:
  - tests/testthat/test-create_toy_data.R
  - tests/testthat/test-create_profiles_table.R
  - tests/testthat/test-create_hedonic_table.R
  - tests/testthat/test-save_data_in_db.R
  vignettes: []
  inflate:
    flat_file: dev/flat_create_database.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_create_report.Rmd:
  path: dev/flat_create_report.Rmd
  state: active
  R: R/create_report.R
  tests: tests/testthat/test-create_report.R
  vignettes: vignettes/e-create-the-sensory-report.Rmd
  inflate:
    flat_file: dev/flat_create_report.Rmd
    vignette_name: e - Create the sensory report
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
flat_perform_multidim_analysis.Rmd:
  path: dev/flat_perform_multidim_analysis.Rmd
  state: active
  R: R/perform_senso_mapping.R
  tests: tests/testthat/test-perform_senso_mapping.R
  vignettes: vignettes/c-perform-the-multidimensional-sensory-analysis--mapping-.Rmd
  inflate:
    flat_file: dev/flat_perform_multidim_analysis.Rmd
    vignette_name: c - Perform the multidimensional sensory analysis (mapping)
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
flat_perform_prefmap.Rmd:
  path: dev/flat_perform_prefmap.Rmd
  state: active
  R:
  - R/perform_prefmap.R
  - R/predict_like.R
  tests:
  - tests/testthat/test-perform_prefmap.R
  - tests/testthat/test-predict_like.R
  vignettes: vignettes/d-perform-the-preference-mapping.Rmd
  inflate:
    flat_file: dev/flat_perform_prefmap.Rmd
    vignette_name: d - Perform the preference mapping
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
flat_perform_unidim_analysis.Rmd:
  path: dev/flat_perform_unidim_analysis.Rmd
  state: active
  R: R/plot_unidim_analysis.R
  tests: tests/testthat/test-plot_unidim_analysis.R
  vignettes: vignettes/b-perform-the-unidimensional-sensory-analysis.Rmd
  inflate:
    flat_file: dev/flat_perform_unidim_analysis.Rmd
    vignette_name: b - Perform the unidimensional sensory analysis
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
flat_query_database.Rmd:
  path: dev/flat_query_database.Rmd
  state: active
  R: R/connect_db.R
  tests: tests/testthat/test-connect_db.R
  vignettes: vignettes/a-query-the-database.Rmd
  inflate:
    flat_file: dev/flat_query_database.Rmd
    vignette_name: a - Query the database
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
