---
title: "flat_perform_multidim_analysis.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(tidyr)
library(FactoMineR)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# `perform_senso_mapping()`: Tranform the sensory data to a large format and perform a PCA

```{r function-perform_senso_mapping}
#' Tranform the sensory data to a large format and perform a PCA
#'
#' @param data_profiles Tibble. Table with the sensory data.
#' @param data_products Tibble. Table with the info about products.
#' @parem ... Other parameters of the FactoMineR::PCA() function.
#'
#' @importFrom tidyr pivot_wider
#' @importFrom dplyr arrange filter mutate pull
#' @importFrom FactoMineR PCA
#' @importFrom glue glue
#' @importFrom plotly plot_ly add_trace layout add_annotations
#' 
#' @return A list of 2 plotly graphs: the PCA ind plot and the PCA var plot
#' @export
perform_senso_mapping <- function(data_profiles,
                                  data_products, 
                                  ...) {
  
  # Transform data to a PROD x ATTRIBUTE table
  data_large <- data_profiles %>%
    pivot_wider(
      names_from = "ATTRIBUTE", 
      values_from = "SCORE"
    ) %>% 
    arrange(PRODUCT)
    
  # Transform to dataframe and add rownames
  data_large <- as.data.frame(data_large)
  rownames(data_large) <- data_large$PRODUCT
  data_large <- data_large[, -1]
  
  # Perform PCA
  res_pca <- PCA(
    X = data_large, 
    graph = FALSE, 
    ...
  )
  
  # Plot the products map
  ## -- Find the products coordinates and take only the 2 first ones 
  coord_prod <- as.data.frame(res_pca$ind$coord[, 1:2])
  colnames(coord_prod) <- c("dim1", "dim2")
  
  ## -- Extra info about products
  vec_info <- data_products %>% 
    filter(PRODUCT %in% rownames(data_large)) %>% 
    arrange(PRODUCT) %>% 
    mutate(text_tooltip = glue("Product {PRODUCT}<br>{INFO}<br>{BRAND}")) %>% 
    pull(text_tooltip)
  
  ## -- Plot
  inter_ind_plot <- plot_ly(data = coord_prod) %>%
    add_trace(
      x = ~ dim1 ,
      y = ~ dim2,
      hoverinfo = 'text',
      text = vec_info,
      type = "scatter",
      mode = "markers",
      marker = list(size = 6, color = "orange"),
      showlegend = TRUE
    ) %>%
    layout(
      legend = list(
        orientation = "h",
        xanchor = "center",
        x = 0.5,
        y = -0.25
      ),
      title = list(
        text = "Representation of the products",
        font = list(size = 14, color = "#444444")
      ),
      xaxis = list(
        zerolinecolor = "#D6D5D5",
        scaleanchor = "y",
        showgrid = FALSE,
        title = paste("Dim 1 - ", round(res_pca$eig[1, 2], 2), "%", sep = ""),
        titlefont = list(color = "#444444", size = 13),
        tickfont = list(size = 10, color = "#444444"),
        showline = TRUE,
        mirror = "ticks",
        linecolor = "#444444",
        linewidth = 1
      ),
      yaxis = list(
        zerolinecolor = "#D6D5D5",
        scaleanchor = "x",
        showgrid = FALSE,
        title = paste("Dim 2 - ", round(res_pca$eig[2, 2], 2), "%", sep =""),
        titlefont = list(color = "#444444", size = 13),
        tickfont = list(size = 10, color = "#444444"),
        showline = TRUE,
        mirror = "ticks",
        linecolor = "#444444",
        linewidth = 1
      )
    )

  # Plot the attributes map
  ## -- Find the attributes coordinates and take only the 2 first one 
  coord_attr <- as.data.frame(res_pca$var$coord[, 1:2])
  colnames(coord_attr) <- c("dim1", "dim2")
  coord_attr[, "attribute"] <- rownames(coord_attr)
  
  ## -- Plot
  inter_var_plot <- plot_ly() %>%
        add_trace(
          data = coord_attr,
          x = ~ dim1 ,
          y = ~ dim2,
          hoverinfo = "text",
          hoverlabel = list(bgcolor = "black", font = list(color = "white")),
          # text = text.tooltip,
          type = "scatter", mode = "markers",
          marker = list(size = 6, color = "white"),
          showlegend = TRUE) %>%
        add_annotations(
          data = coord_attr,
          axref = "x", 
          ax = ~ dim1, 
          aref = "x", 
          x = 0,
          ayref = "y", 
          ay = ~ dim2, 
          aref = "y", 
          y = 0,
          text = coord_attr$attribute, 
          arrowhead = 0, arrowcolor = "black") %>%
    layout(
      shapes = list(
        list(type = "circle",
             xref = 'x', x0 = -1, x1 = 1,
             yref = 'y', y0 = -1, y1 = 1,
             fillcolor = "orange", 
             line = list(color = "orange"),
             opacity = 0.1)),
      legend = list(
        orientation = "h",
        xanchor = "center",
        x = 0.5,
        y = -0.25,
        font = list(color = "transparent")
      ),
      title = list(text = "Representation of the sensory attributes", font = list(
        size = 14, color = "#444444"
      )),
      xaxis = list(
        zerolinecolor = "#D6D5D5",
        scaleanchor = "y",
        showgrid = FALSE,
        title = paste("Dim 1 - ", round(res_pca$eig[1, 2], 2), "%", sep =
                        ""),
        titlefont = list(color = "#444444", size = 13),
        tickfont = list(size = 10, color = "#444444"),
        showline = TRUE,
        mirror = "ticks",
        linecolor = "#444444",
        linewidth = 1
      ),
      yaxis = list(
        zerolinecolor = "#D6D5D5",
        scaleanchor = "x",
        showgrid = FALSE,
        title = paste("Dim 2 - ", round(res_pca$eig[2, 2], 2), "%", sep =
                        ""),
        titlefont = list(color = "#444444", size = 13),
        tickfont = list(size = 10, color = "#444444"),
        showline = TRUE,
        mirror = "ticks",
        linecolor = "#444444",
        linewidth = 1
      )
    )

  return(
    list(
      res_pca = res_pca,
      inter_ind_plot = inter_ind_plot,
      inter_var_plot = inter_var_plot
    )
  )
  
}
```

```{r examples-perform_senso_mapping, out.width='100%', out.height='100%'}
data("data_profiles_toy")
data("data_products_toy")

res_mapping <- perform_senso_mapping(
  data_profiles = data_profiles_toy,
  data_products = data_products_toy
)

res_mapping$inter_ind_plot # individuals (products) plot
res_mapping$inter_var_plot # variables (sensory attributes) plot
```

```{r tests-perform_senso_mapping}
test_that("perform_senso_mapping works", {

  data("data_profiles_toy")
  data("data_products_toy")
  
  plots_mapping <- perform_senso_mapping(
    data_profiles = data_profiles_toy,
    data_products = data_products_toy
  )
  
  expect_true(inherits(plots_mapping$inter_ind_plot, "plotly"))
  expect_true(inherits(plots_mapping$inter_var_plot, "plotly"))

})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_perform_multidim_analysis.Rmd", 
  vignette_name = "c - Perform the multidimensional sensory analysis (mapping)", 
  check = FALSE,
  overwrite = TRUE,
  open_vignette = FALSE
  )
```

