---
title: "flat_query_database.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# `connect_db()`: Connect to the sensory database

With `connect_db()`, you can open a connection to query the sensory database. The database is stored in the package for demonstration purposes.

```{r function-connect_db}
#' Connect to the sensory database
#'
#' @param dbdir Character. Path to the sensory database.
#' @param read_only Logical. Define a read only connection or not.
#' 
#' @importFrom DBI dbConnect
#' @importFrom RSQLite SQLite
#' @importFrom tools file_ext
#'
#' @return The connection to the database.
#' 
#' @export
connect_db <- function(dbdir = app_sys("database", "sensory_db.sqlite"), 
                       read_only = TRUE) {
  
  # Check parameters
  if (isFALSE(file_ext(dbdir) == "sqlite")) {
    stop("The database you provided is not a SQLite database.")
  }
  
  if (isFALSE(file.exists(dbdir))) {
    warning("The database you provided does not exist. Please specify a correct 'dbdir' parameter. Or a new database will be created.")
  }
  
  con_db <- tryCatch(
    
    DBI::dbConnect(
      RSQLite::SQLite(),
      dbdir,
      read_only = read_only
      ), error = function(e) {
      message("Connection to sensory database failed")
        
    })
 
  return(con_db)

}
```

```{r examples-connect_db}
con_db <- connect_db()

# List tables in the sensory database
DBI::dbListTables(con_db)

# Read the sensory profiles
dplyr::tbl(con_db, dplyr::sql("SELECT * FROM PROFILES LIMIT 10"))

# Read the hedonic data
dplyr::tbl(con_db, dplyr::sql("SELECT * FROM HEDONIC LIMIT 10"))

# Read the sessions data
dplyr::tbl(con_db, dplyr::sql("SELECT * FROM SESSIONS"))

# Read the products data
dplyr::tbl(con_db, dplyr::sql("SELECT * FROM PRODUCTS LIMIT 10"))

# Disconnect
DBI::dbDisconnect(con_db, shutdown = TRUE)
```

```{r tests-connect_db}
test_that("query_database works", {

  con_db <- connect_db()
  
  # List tables in the sensory database
  expect_equal(
    object = DBI::dbListTables(con_db), 
    expected = c("HEDONIC", "PRODUCTS", "PROFILES", "SESSIONS")
  )
  
  # Disconnect
  DBI::dbDisconnect(con_db, shutdown = TRUE)
  
  # Test an error if the database does not exist
  expect_warning(
    object = connect_db(dbdir = "random/sensory_db.sqlite"), 
    regexp = "The database you provided does not exist"
  )
  
  # Test an error if the database is not a SQLite
  expect_error(
    object = connect_db(dbdir = "random/sensory_db.duckdb"), 
    regexp = "The database you provided is not a SQLite database"
  )
  
})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_query_database.Rmd", 
  vignette_name = "a - Query the database", 
  check = FALSE, 
  overwrite = TRUE
)
```

