# WARNING - Generated by {fusen} from dev/flat_perform_multidim_analysis.Rmd: do not edit by hand

test_that("perform_senso_mapping works", {

  data("data_profiles_toy")
  data("data_products_toy")
  
  plots_mapping <- perform_senso_mapping(
    data_profiles = data_profiles_toy,
    data_products = data_products_toy
  )
  
  expect_true(inherits(plots_mapping$inter_ind_plot, "plotly"))
  expect_true(inherits(plots_mapping$inter_var_plot, "plotly"))

})
