# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

test_that("create_toy_data works", {
  
  withr::with_seed(seed = 123, {
    
    list_profiles_data <- list()
    
    for (i in 1:6) {
      list_profiles_data[[i]] <- create_toy_data(data = senso.cocktail) %>%
        mutate(SESSION = paste0("SESS230", i))
    }
    
    expect_equal(
      object = create_profiles_table(list_data = list_profiles_data)[1:10, ],
      expected = structure(
        list(
          SESSION = c(
            "SESS2301",
            "SESS2301",
            "SESS2301",
            "SESS2301",
            "SESS2301",
            "SESS2301",
            "SESS2301",
            "SESS2301",
            "SESS2301",
            "SESS2301"
          ),
          PRODUCT = c(
            "PROD1",
            "PROD1",
            "PROD1",
            "PROD1",
            "PROD1",
            "PROD1",
            "PROD1",
            "PROD1",
            "PROD1",
            "PROD1"
          ),
          ATTRIBUTE = c(
            "Color Intensity",
            "Odor Intensity",
            "Odor Orange",
            "Odor Banana",
            "Odor Mango",
            "Odor Lemon",
            "Strongness",
            "Sweet",
            "Acidity",
            "Bitterness"
          ),
          SCORE = c(
            7.39785735344779,
            6.08118347822924,
            4.64512566104502,
            3.86079811833632,
            4.88654177352442,
            6.25576418589989,
            9.14566599301658,
            4.59045029171084,
            6.12147636586987,
            0.398463826425407
          )
        ),
        row.names = c(NA,-10L),
        class = c("tbl_df", "tbl", "data.frame")
      )
    )
    
  })
})
