# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

test_that("save_data_in_duckdb works", {
  
  # Create a temp dir
  temp_directory <- tempfile(pattern = "db-")
  dir.create(temp_directory)

  # Save data in the database
  expect_error(save_data_in_duckdb(
    table = iris,
    name_table = "IRIS",
    dbdir = file.path(temp_directory, "sensory_db.duckdb")
  ),
  NA)

  })
