# WARNING - Generated by {fusen} from dev/flat_perform_multidim_analysis.Rmd: do not edit by hand

test_that("perform_senso_mapping works", {

  data("data_sensory_toy")
  data("data_products_toy")
  
  plots_mapping <- perform_senso_mapping(
    data_sensory = data_sensory_toy,
    data_products = data_products_toy
  )
  
  expect_true(inherits(plots_mapping$inter_ind_plot, "plotly"))
  expect_true(inherits(plots_mapping$inter_var_plot, "plotly"))
  
  # Test an error is the parameter is not a dataframe
  expect_error(
    object = perform_senso_mapping(
      data_sensory = data_sensory_toy,
      data_products = 1), 
    regexp = "The data 'data_products' you provided is not a dataframe"
  )
  
  expect_error(
    object = perform_senso_mapping(
      data_sensory = 1,
      data_products = data_products_toy), 
    regexp = "The data 'data_sensory' you provided is not a dataframe"
  )

})
