# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

test_that("create_hedonic_table_one_session works", {
  
  withr::with_seed(seed = 123, {
    
    dta_hedonic <- create_hedonic_table_one_session(
      nbprod = 5,
      nbconsumers = 2
    )
    
    expect_equal(object = dta_hedonic,
                 expected = structure(
                   list(
                     PRODUCT = c("PROD1", "PROD2", "PROD3", "PROD4",
                                 "PROD5"),
                     `1` = c(3L, 3L, 10L, 2L, 6L),
                     `2` = c(5L, 4L, 6L, 9L,
                             10L)
                   ),
                   row.names = c(NA,-5L),
                   class = c("tbl_df", "tbl", "data.frame")
                 )
    
    )
    
  })
})
