# WARNING - Generated by {fusen} from dev/flat_perform_unidim_analysis.Rmd: do not edit by hand

test_that("perform_unidim_analysis works", {

  data("data_profiles_toy")
  
  my_unidim_plots <- plot_unidim_analysis(
    data = data_profiles_toy
  )
  
  expect_true(inherits(my_unidim_plots$stat_plot, "gg"))
    
  expect_true(inherits(my_unidim_plots$inter_plot, "plotly"))

})
