# WARNING - Generated by {fusen} from dev/flat_query_database.Rmd: do not edit by hand

test_that("query_database works", {

  con_db <- connect_db()
  
  # List tables in the sensory database
  expect_equal(
    object = DBI::dbListTables(con_db), 
    expected = c("HEDONIC", "PRODUCTS", "PROFILES", "SESSIONS")
  )
  
  # Disconnect
  DBI::dbDisconnect(con_db, shutdown = TRUE)
  
})
