# WARNING - Generated by {fusen} from dev/flat_query_database.Rmd: do not edit by hand

test_that("query_database works", {

  con_db <- connect_db()
  
  # List tables in the sensory database
  expect_equal(
    object = DBI::dbListTables(con_db), 
    expected = c("HEDONIC", "PRODUCTS", "PROFILES", "SESSIONS")
  )
  
  # Disconnect
  DBI::dbDisconnect(con_db, shutdown = TRUE)
  
  # Test an error if the database does not exist
  expect_warning(
    object = connect_db(dbdir = "random/sensory_db.sqlite"), 
    regexp = "The database you provided does not exist"
  )
  
  # Test an error if the database is not a SQLite
  expect_error(
    object = connect_db(dbdir = "random/sensory_db.duckdb"), 
    regexp = "The database you provided is not a SQLite database"
  )
  
})
