# WARNING - Generated by {fusen} from dev/flat_perform_prefmap.Rmd: do not edit by hand

test_that("perform_prefmap works", {

  data("data_hedonic_toy")
  
  res_mapping <- perform_senso_mapping(
    data_profiles = data_profiles_toy,
    data_products = data_products_toy
  )
  
  plot_prefmap <- perform_prefmap(
    res_mapping = res_mapping,
    data_hedonic = data_hedonic_toy
  )
  
  expect_true(inherits(plot_prefmap, "plotly"))
  
  # Test an error is the parameter is not a PCA result
  expect_error(
    object = perform_prefmap(
      res_mapping = 1,
      data_hedonic = data_hedonic_toy
    ),
    regexp = "Are you sure the parameter 'res_mapping'"
  )
  
  expect_error(
    object = perform_prefmap(
      res_mapping = list(a = 1, b = 2, c = 3),
      data_hedonic = data_hedonic_toy
    ),
    regexp = "Are you sure the parameter 'res_mapping'"
  )
  
  expect_error(
    object = perform_prefmap(
      res_mapping = list(res_pca = 1, inter_ind_plot = 2, inter_var_plot = 3),
      data_hedonic = data_hedonic_toy
    ),
    regexp = "Are you sure the parameter 'res_mapping'"
  )
  
  # Test an error is the parameter is not a dataframe
  expect_error(
    object = perform_prefmap(
      res_mapping = res_mapping,
      data_hedonic = 1), 
    regexp = "The data 'data_hedonic' you provided is not a dataframe"
  )

})
