# WARNING - Generated by {fusen} from dev/flat_create_report.Rmd: do not edit by hand

test_that("create_report works", {
  
  # Create temporary directory
  my_temp_dir <- tempfile()
  dir.create(my_temp_dir)
  
  # Create the sensory report
  res_info_report <- create_report(
    author = "Swann",
    session = "SESS2301",
    products = c("PROD1", "PROD2",
                 "PROD3", "PROD4",
                 "PROD5", "PROD6"),
    output_dir = my_temp_dir
  )
  
  # Check if the file exists
  expect_true(file.exists(
    file.path(
      res_info_report$output_dir_report,
      res_info_report$output_file_report
    )
  ))
  
  # Delete temporary directory
  unlink(my_temp_dir, recursive = TRUE)

})
