# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

test_that("create_sorting_data_one_session works", {
  
  withr::with_seed(seed = 123, {
    
    dta_sorting <- create_sorting_data_one_session(
      nbprod = 5,
      nbconsumers = 2
    )
    
    expect_equal(object = dta_sorting,
                 expected = structure(
                   list(
                     PRODUCT = c("PROD1", "PROD2", "PROD3", "PROD4",
                                 "PROD5"),
                     `1` = c("rasperry", "rasperry", "citrus", "pear",
                             "citrus"),
                     `2` = c("sugar", "sugar", "pear", "citrus",
                             "apple")
                   ),
                   row.names = c(NA, -5L),
                   class = c("tbl_df", "tbl", "data.frame")
                 ))
    
  })
})
