# WARNING - Generated by {fusen} from dev/flat_query_database.Rmd: do not edit by hand

#' Connect to the sensory database
#'
#' @param dbdir Character. Path to the sensory database.
#' @param read_only Logical. Define a read only connection or not.
#' 
#' @importFrom DBI dbConnect
#' @importFrom RSQLite SQLite
#' @importFrom tools file_ext
#'
#' @return The connection to the database.
#' 
#' @export
#' @examples
#' con_db <- connect_db()
#'
#' # List tables in the sensory database
#' DBI::dbListTables(con_db)
#'
#' # Read the sensory profiles
#' dplyr::tbl(con_db, dplyr::sql("SELECT * FROM PROFILES LIMIT 10"))
#'
#' # Read the hedonic data
#' dplyr::tbl(con_db, dplyr::sql("SELECT * FROM HEDONIC LIMIT 10"))
#'
#' # Read the sessions data
#' dplyr::tbl(con_db, dplyr::sql("SELECT * FROM SESSIONS"))
#'
#' # Read the products data
#' dplyr::tbl(con_db, dplyr::sql("SELECT * FROM PRODUCTS LIMIT 10"))
#'
#' # Disconnect
#' DBI::dbDisconnect(con_db, shutdown = TRUE)
connect_db <- function(dbdir = app_sys("database", "sensory_db.sqlite"), 
                       read_only = TRUE) {
  
  # Check parameters
  if (isFALSE(file_ext(dbdir) == "sqlite")) {
    stop("The database you provided is not a SQLite database.")
  }
  
  if (isFALSE(file.exists(dbdir))) {
    warning("The database you provided does not exist. Please specify a correct 'dbdir' parameter. Or a new database will be created.")
  }
  
  con_db <- tryCatch(
    
    DBI::dbConnect(
      RSQLite::SQLite(),
      dbdir,
      read_only = read_only
      ), error = function(e) {
      message("Connection to sensory database failed")
        
    })
 
  return(con_db)

}
