# WARNING - Generated by {fusen} from dev/flat_query_database.Rmd: do not edit by hand

#' Connect to the sensory database
#'
#' @param dbdir Character. Path to the sensory database.
#' 
#' @importFrom DBI dbConnect
#' @importFrom RSQLite SQLite
#'
#' @return The connection to the database.
#' 
#' @export
#' @examples
#' con_db <- connect_db()
#'
#' # List tables in the sensory database
#' DBI::dbListTables(con_db)
#'
#' # Read the sensory profiles
#' # dplyr::tbl(con_db, "PROFILES")
#'   
#' # Disconnect
#' DBI::dbDisconnect(con_db, shutdown = TRUE)
connect_db <- function(dbdir = app_sys("database", "sensory_db.sqlite"), 
                       read_only = TRUE) {
  
  con_db <- tryCatch(
    
    DBI::dbConnect(
      RSQLite::SQLite(),
      dbdir,
      read_only = read_only
      ), error = function(e) {
      message("Connection to sensory database failed")
        
    })
 
  return(con_db)

}
