# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

#' Create toy sensory datasets (sensory profiles & hedonic)
#' 
#' Use the cocktail datasets of the {SensoMineR} package
#' 
#' @param data Dataframe. Original dataset to be used.
#' @param mean Numeric. Mean to be used in rnorm to generate noise.
#' @param sd Numeric. Sd to be used in rnorm to generate noise.
#' 
#' @importFrom stats rnorm
#'
#' @return Tibble. The original dataset with some noise (uniform distribution)
#' @noRd
#' @examples
#' data(cocktail)
#'
#' create_toy_data(
#'   data = senso.cocktail
#' )
#'
#' create_toy_data(
#'   data = hedo.cocktail
#' )
create_toy_data <- function(data, 
                            mean = 0, 
                            sd = 1){
  
  toy_data <- data +
    matrix(rnorm(
      n = nrow(data) * ncol(data),
      mean = mean,
      sd = sd
    ),
    nrow = nrow(data),
    ncol = ncol(data))
    
  return(toy_data)
  
}
