# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

#' Create the toy sensory profiles table
#' 
#' @importFrom purrr map
#' @importFrom dplyr mutate rename bind_rows
#' @importFrom tidyr pivot_longer
#' @importFrom stringr str_replace_all str_to_title
#' 
#' @return Tibble. The toy sensory profiles table, in a long format.
#' @noRd
#' @examples
#' list_profiles_data <- list()
#'
#' for (i in 1:6) {
#'   list_profiles_data[[i]] <- create_toy_data(
#'     data = senso.cocktail
#'     ) %>% 
#'     mutate(SESSION = paste0("SESS230", i))
#' }
#'
#' create_profiles_table(
#'   list_data = list_profiles_data
#' )
create_profiles_table <- function(list_data){
  
  profiles_table <- list_data %>%
    map(
      ~ .x %>%
        mutate(PRODUCT = paste0("PROD", rownames(list_data[[1]]))) %>%
        pivot_longer(cols = -c(PRODUCT, SESSION)) %>%
        rename(ATTRIBUTE = name,
               SCORE = value) %>%
        mutate(
          ATTRIBUTE = str_replace_all(ATTRIBUTE, "\\.", " "),
          ATTRIBUTE = str_to_title(ATTRIBUTE)
        )
    ) %>% 
    bind_rows()
    
  return(profiles_table)
  
}
