# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

#' Create the toy sensory hedonic data for one session
#' 
#' @param nbprod Integer. Number of products.
#' @param nbconsumers Integer. Number of consumers who assessed the products.
#' 
#' @importFrom purrr map_dfc set_names
#' @importFrom dplyr mutate select
#' @importFrom tidyselect everything
#' 
#' @return Tibble. The toy hedonic data for one session.
#' 
#' @noRd
#' @examples
#' create_hedonic_table_one_session(
#'   nbprod = 6,
#'   nbconsumers = 10
#' )
create_hedonic_table_one_session <- function(nbprod,
                                             nbconsumers) {
  
  hedonic_table <- 1:nbconsumers |> 
    map_dfc( ~ c(
      sample(1:5,
             size = nbprod / 2,
             replace = TRUE),
      sample(6:10,
             size = nbprod / 2, 
             replace = TRUE)
    )) |> 
    set_names(1:nbconsumers) |> 
    mutate(PRODUCT = paste0("PROD", 1:nbprod)) |>
    select(PRODUCT, everything())
  
  return(hedonic_table)
  
}
