# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

#' Create the toy senso table or the hedonic table
#' 
#' @param nbprod Integer. Number of sessions.
#' @param nbprod Integer. Number of products.
#' @param nbconsumers Integer. Number of consumers who assessed the products.
#' @param ... Other arguments of \link[sensoreport]{create_sorting_data_one_session}.
#' 
#' @importFrom dplyr mutate rename bind_rows
#' @importFrom tidyr pivot_longer
#' @importFrom purrr map_dfr
#' 
#' @return Tibble. The toy senso or hedo table.
#' 
#' @noRd
#' @examples
#' create_toy_table(
#'   nbsessions = 2, 
#'   nbprod = 4, 
#'   nbconsumers = 4,
#'   type = "senso"
#' )
#'
#' create_toy_table(
#'   nbsessions = 2, 
#'   nbprod = 4, 
#'   nbconsumers = 4,
#'   type = "hedo"
#' )
create_toy_table <- function(nbsessions,
                             nbprod, 
                             nbconsumers, 
                             type = c("senso", "hedo"),
                             ...) {
  
  type <- match.arg(type)
  
  if (type == "senso") {
    
    toy_table <- 1:nbsessions |> 
      map_dfr(~ create_sorting_data_one_session(
        nbprod = nbprod,
        nbconsumers = nbconsumers, 
        ...
      ) |> 
        mutate(SESSION = paste0("SESS230", .x))) |> 
      pivot_longer(cols = -c(PRODUCT, SESSION)) |>
      rename(CONSUMER = name,
             GROUP = value) |> 
      bind_rows()
    
  } else if (type == "hedo") {
    
    toy_table <- 1:nbsessions |> 
      map_dfr(~ create_hedonic_table_one_session(
        nbprod = nbprod,
        nbconsumers = nbconsumers
      ) |> 
        mutate(SESSION = paste0("SESS230", .x))) |> 
      pivot_longer(cols = -c(PRODUCT, SESSION)) |>
      rename(CONSUMER = name,
             SCORE = value) |> 
      bind_rows()
    
  }
  
  return(toy_table)
 
}
