# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

#' Create the toy sensory hedonic table
#' 
#' @importFrom purrr map
#' @importFrom dplyr mutate rename bind_rows
#' @importFrom tidyr pivot_longer
#' 
#' @return Tibble. The toy sensory profiles table, in a long format.
#' @noRd
#' @examples
#' list_hedonic_data <- list()
#'
#' for (i in 1:6) {
#'   list_hedonic_data[[i]] <- create_toy_data(
#'     data = hedo.cocktail
#'     ) %>% 
#'     mutate(SESSION = paste0("SESS230", i))
#' }
#'
#' create_hedonic_table(
#'   list_data = list_hedonic_data
#' )
create_hedonic_table <- function(list_data){
  
  hedonic_table <- list_data %>%
    map(
      ~ .x %>%
        mutate(PRODUCT = paste0("PROD", rownames(list_data[[1]]))) %>%
        pivot_longer(cols = -c(PRODUCT, SESSION)) %>%
        rename(CONSUMER = name,
               SCORE = value)
    ) %>% 
    bind_rows()
    
  return(hedonic_table)
  
}
