# WARNING - Generated by {fusen} from dev/flat_create_report.Rmd: do not edit by hand

#' Create the reproducible HTML sensory report
#'
#' @param author Character. Author of the report.
#' @param session Character. ID of the sensory session.
#' @param products Character. Vector of products to include into the report.
#' @param output_dir Character. Path of the folder to save the report.
#' @param report_template Character. Path of the folder containing the report template.
#' 
#' @importFrom withr with_dir
#' @importFrom quarto quarto_render
#' @importFrom stringr str_remove_all
#' 
#' @return A list with the folder and the file of the created report.
#' 
#' @export
#' @examples
#' # Create a temporary directory
#' my_temp_dir <- tempfile()
#' dir.create(my_temp_dir)
#'
#' # Create the sensory report
#' res_info_report <- create_report(
#'   author = "Swann",
#'   session = "SESS2301",
#'   products = c("PROD1", "PROD2", 
#'                "PROD3", "PROD4", 
#'                "PROD5", "PROD6"),
#'   output_dir = my_temp_dir
#' )
#'
#' # Open the sensory report
#' browseURL(
#'   file.path(
#'     res_info_report$output_dir_report, 
#'     res_info_report$output_file_report
#'   )
#' )
#'
#' # Delete temporary directory
#' unlink(my_temp_dir, recursive = TRUE)
create_report <- function(author,
                          session,
                          products,
                          output_dir,
                          report_template = app_sys("report")) {
  
  # Create the list of parameters
  list_param_report <- list(
    author = author,
    session = session,
    products = products
  )
  
  # Get the name of the html file
  output_report <- paste0(
    str_remove_all(Sys.time(), "-|:| |UTC"), 
    "-sensory_report.html"
  )
  
  # Move the .qmd template into the temp directory
  fs::dir_copy(
    path = report_template,
    new_path = output_dir
  )

  # Render the report
  with_dir(
    file.path(output_dir, basename(report_template)), {
      quarto_render(
        input = "report_template.qmd",
        execute_params = list_param_report,
        output_file = output_report,
        quiet = TRUE
      )
  })
  
  return(
    list(
      output_dir_report = file.path(output_dir, basename(report_template)),
      output_file_report = output_report
    )
  )
  
}
