# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

#' Create the toy sorting task data for one session
#' 
#' @param nbprod Integer. Number of products.
#' @param nbconsumers Integer. Number of consumers who assessed the products.
#' @param possible_groups Character. Vector of possible names of groups.
#' 
#' @importFrom purrr map_dfc set_names
#' @importFrom dplyr mutate select
#' @importFrom tidyselect everything
#' 
#' @return Tibble. The toy sorting task table.
#' 
#' @noRd
#' @examples
#' create_sorting_data_one_session(
#'   nbprod = 6,
#'   nbconsumers = 10
#' )
create_sorting_data_one_session <- function(nbprod,
                                            nbsessions,
                                            nbconsumers,
                                            possible_groups = c("vanilla",
                                                                "sugar",
                                                                "citrus",
                                                                "flowers",
                                                                "apple",
                                                                "pear",
                                                                "rasperry")) {
  
  sorting_table <- 1:nbconsumers |> 
    map_dfc(~ sample(
      possible_groups, 
      size = nbprod, 
      replace = TRUE)) |> 
    set_names(1:nbconsumers) |> 
    mutate(PRODUCT = paste0("PROD", 1:nbprod)) |> 
    select(PRODUCT, everything())
  
  return(sorting_table)
  
}
