# WARNING - Generated by {fusen} from dev/flat_perform_unidim_analysis.Rmd: do not edit by hand

#' Create the plot with the unidimensional analysis
#' 
#' @param data_profiles Tibble. The sensory data.
#' 
#' @importFrom ggplot2 ggplot aes geom_col labs facet_wrap theme_minimal theme element_blank
#' @importFrom plotly ggplotly
#' @importFrom dplyr vars
#' 
#' @return A ggplotly
#' @export
#' @examples
#' data("data_profiles_toy")
#'
#' plot_unidim_analysis(
#'   data_profiles = data_profiles_toy
#' )
plot_unidim_analysis <- function(data_profiles) {
  
  # Check parameters
  if (isFALSE(is.data.frame(data_profiles))) {
    stop("The data you provided is not a dataframe.")
  }
  
  # Static plot
  unidim_plot <- ggplot(data = data_profiles) +
    aes(x = PRODUCT,
        y = SCORE,
        fill = PRODUCT) +
    geom_col() +
    labs(x = "",
         y = "Intensity on a 0-10 scale") +
    facet_wrap(facets = vars(ATTRIBUTE)) +
    theme_minimal() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())
  
  # Interactive plot
  inter_plot <- ggplotly(
    p = unidim_plot,
    tooltip = c("x", "y")
  )
  
  return(inter_plot)
  
}
