# WARNING - Generated by {fusen} from dev/flat_perform_prefmap.Rmd: do not edit by hand

#' Predict if a given panelist likes a given fictional product or not
#' 
#' @param data_coord_real Dataframe. Table with coordinates of real products.
#' @param data_grid Dataframe. Table with coordinates of fictional products (grid).
#' @param data_hedonic_large Dataframe. Table with hedonic data.
#' @param panelist_name Character. Name of the panelist.
#'
#' @importFrom tibble tibble
#' @importFrom stats lm predict.lm
#' 
#' @return A table with the coordinates of the fictional products. A 0 if the panelist does not like it, a 1 otherwise.
#' @noRd
#' @examples
#' data("data_grid_toy")
#' data("data_hedonic_toy")
#' data("data_coord_real_toy")
#'
#' data_hedonic_large_toy <- data_hedonic_toy |> 
#'   tidyr::pivot_wider(
#'     names_from = CONSUMER,
#'     values_from = SCORE
#'   )
#'
#' predict_like(
#'   data_coord_real = data_coord_real_toy,
#'   data_grid = data_grid_toy,
#'   data_hedonic_large = data_hedonic_large_toy,
#'   panelist_name = "1"
#' )
predict_like <- function(data_coord_real,
                         data_grid,
                         data_hedonic_large, 
                         panelist_name){
    
  # Combine the real coordinates and the liking score
  data_coord_real_liking <- tibble(
    dim1 = data_coord_real$dim1,
    dim2 = data_coord_real$dim2,
    dim1dim2 = data_coord_real$dim1dim2,
    liking_score = data_hedonic_large[[panelist_name]]
  )

  # Get the linear model to predict the liking score according to coordinates
  mod_predict_liking <- lm(
    formula = liking_score ~ dim1 + dim2 + dim1dim2, 
    data = as.data.frame(data_coord_real_liking)
  )

  # Predict the liking score for each point of the fictional grid
  predict_liking_grid <- predict.lm(
    object = mod_predict_liking, 
    newdata = data_grid, 
    type = "response"
  )
  
  # Find the mean of liking scores for the panelist
  mean_liking_panelist <- mean(data_coord_real_liking$liking_score)
  
  # Define if the panelist like or not
  # -- like = the predicted score is higher or = than the mean of the panelist
  predict_liking_grid <- as.numeric(predict_liking_grid >= mean_liking_panelist)
  # 0 means he/she does not like
  # 1 means he/she likes
  
  # Return the matrix
  res_grid_with_liking <- matrix(
    predict_liking_grid,
    nrow = length(unique(data_grid$dim1)), 
    ncol = length(unique(data_grid$dim2))
  )
  
  return(res_grid_with_liking)

}
