# WARNING - Generated by {fusen} from dev/flat_create_database.Rmd: do not edit by hand

#' Save toy sensory datasets in the duckdb
#' 
#' @param table Dataframe. Table to be saved.
#' @param name_table Character. Name of the table to be saved.
#' @param dbdir Character. Directory of the database.
#' @param overwrite Boolean. If an existing table can be overwritten.
#' 
#' @importFrom DBI dbConnect dbWriteTable dbDisconnect
#' @importFrom here here
#'
#' @return Nothing. Used for side effect.
#' 
#' @noRd
#' @examples
#' # Create a temp dir
#' temp_directory <- tempfile(pattern = "db-")
#' dir.create(temp_directory)
#'
#' # Save data in the database
#' save_data_in_db(
#'   table = iris,
#'   name_table = "IRIS",
#'   dbdir = file.path(temp_directory, "sensory_db.sqlite")
#' )
#'
#' # Read data in the database
#' con_db <- connect_db(
#'   dbdir = file.path(temp_directory, "sensory_db.sqlite")
#' )
#'
#' DBI::dbReadTable(
#'   con_db, 
#'   "IRIS"
#' )
#'
#' DBI::dbDisconnect(con_db)
save_data_in_db <- function(table, 
                            name_table, 
                            dbdir = here::here("inst", "database", "sensory_db.sqlite"),
                            overwrite = FALSE){
  
  # Open the database (or create a new one if it does not exist)
  con_db <- connect_db(
    dbdir = dbdir,
    read_only = FALSE
  )

  # Write the table in the database
  dbWriteTable(
    con_db, 
    name = name_table, 
    value = table, 
    overwrite = overwrite
  )
  
  # Disconnect
  DBI::dbDisconnect(con_db, shutdown = TRUE)

}
